# Generated by Django 3.2.4 on 2023-09-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_schange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='msg',
        ),
    ]
